services:
  db:
    image: postgres:latest
    container_name: bank_bot_db
    env_file:
      - .env
    restart: on-failure
    ports:
      - "3334:5432"
    volumes:
      - bank_bot_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: bank_bot_redis
    env_file:
      - .env
    restart: on-failure
    ports:
      - "6379:6379"

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: ./entrypoint_app.sh


volumes:
  bank_bot_data:




