version: '3.7'
services:
  db:
    image: postgres:latest
    container_name: bank_bot_db
    env_file:
      - .env
    restart: on-failure
    ports:
      - "3334:5432"

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
