"""

Revision ID: 1da419b9501a
Revises: 8ff7b6ad0c99
Create Date: 2025-02-06 19:10:54.188152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da419b9501a'
down_revision: Union[str, None] = '8ff7b6ad0c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scheduled_credit_jobs_user_id_fkey', 'scheduled_credit_jobs', type_='foreignkey')
    op.drop_column('scheduled_credit_jobs', 'user_id')
    op.drop_constraint('scheduled_deposit_jobs_user_id_fkey', 'scheduled_deposit_jobs', type_='foreignkey')
    op.drop_column('scheduled_deposit_jobs', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_deposit_jobs', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('scheduled_deposit_jobs_user_id_fkey', 'scheduled_deposit_jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('scheduled_credit_jobs', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('scheduled_credit_jobs_user_id_fkey', 'scheduled_credit_jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
