"""

Revision ID: 203e3937b4d5
Revises: 6dec03a814cb
Create Date: 2025-01-31 23:11:52.600628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '203e3937b4d5'
down_revision: Union[str, None] = '6dec03a814cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_jobs', sa.Column('name', sa.Enum('DEBT_REMINDER', 'BLOCK_USER', 'DEPOSIT_PAYMENT', name='scheduledjobtype'), nullable=False))
    op.drop_column('scheduled_jobs', 'type')
    op.drop_column('scheduled_jobs', 'deal_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_jobs', sa.Column('deal_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('scheduled_jobs', sa.Column('type', postgresql.ENUM('DEBT_REMINDER', 'BLOCK_USER', 'DEPOSIT_PAYMENT', name='scheduledjobtype'), autoincrement=False, nullable=False))
    op.drop_column('scheduled_jobs', 'name')
    # ### end Alembic commands ###
