"""

Revision ID: 3a02ebc264a4
Revises: 6e52a52b071c
Create Date: 2025-01-26 00:44:15.205030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a02ebc264a4'
down_revision: Union[str, None] = '6e52a52b071c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels_guide', sa.Column('telegram_channel_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_channels_guide_telegram_channel_id'), 'channels_guide', ['telegram_channel_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channels_guide_telegram_channel_id'), table_name='channels_guide')
    op.drop_column('channels_guide', 'telegram_channel_id')
    # ### end Alembic commands ###
