"""

Revision ID: 5643686adbeb
Revises: 5c7756d37c3d
Create Date: 2025-02-02 21:49:49.776317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5643686adbeb'
down_revision: Union[str, None] = '5c7756d37c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_credit_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apscheduler_job_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credit_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DEBT_REMINDER', 'BLOCK_USER', name='creditjobtype'), nullable=False),
    sa.Column('run_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_credit_jobs_apscheduler_job_id'), 'scheduled_credit_jobs', ['apscheduler_job_id'], unique=True)
    op.create_table('scheduled_deposit_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apscheduler_job_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deposit_id', sa.Integer(), nullable=False),
    sa.Column('run_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_deposit_jobs_apscheduler_job_id'), 'scheduled_deposit_jobs', ['apscheduler_job_id'], unique=True)
    op.drop_index('ix_scheduled_jobs_apscheduler_job_id', table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('run_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('apscheduler_job_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='scheduled_jobs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='scheduled_jobs_pkey')
    )
    op.create_index('ix_scheduled_jobs_apscheduler_job_id', 'scheduled_jobs', ['apscheduler_job_id'], unique=True)
    op.drop_index(op.f('ix_scheduled_deposit_jobs_apscheduler_job_id'), table_name='scheduled_deposit_jobs')
    op.drop_table('scheduled_deposit_jobs')
    op.drop_index(op.f('ix_scheduled_credit_jobs_apscheduler_job_id'), table_name='scheduled_credit_jobs')
    op.drop_table('scheduled_credit_jobs')
    # ### end Alembic commands ###
