"""

Revision ID: 5c7756d37c3d
Revises: b3995e5d441e
Create Date: 2025-02-02 21:00:09.473293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c7756d37c3d'
down_revision: Union[str, None] = 'b3995e5d441e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduled_jobs', 'name',
               existing_type=postgresql.ENUM('DEBT_REMINDER', 'BLOCK_USER', 'DEPOSIT_PAYMENT', name='scheduledjobtype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduled_jobs', 'name',
               existing_type=sa.String(),
               type_=postgresql.ENUM('DEBT_REMINDER', 'BLOCK_USER', 'DEPOSIT_PAYMENT', name='scheduledjobtype'),
               existing_nullable=False)
    # ### end Alembic commands ###
