"""

Revision ID: 6dec03a814cb
Revises: aa1d72002580
Create Date: 2025-01-31 23:10:06.374424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dec03a814cb'
down_revision: Union[str, None] = 'aa1d72002580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_jobs', 'deal_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_jobs', sa.Column('deal_type', postgresql.ENUM('CREDIT', 'DEPOSIT', name='dealtype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
