"""

Revision ID: 6e52a52b071c
Revises: 
Create Date: 2025-01-20 17:15:52.873272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6e52a52b071c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    cat_images_guide_table = op.create_table('cat_images_guide',
                                             sa.Column('id', sa.Integer(), nullable=False),
                                             sa.Column('url', sa.String(length=255), nullable=False),
                                             sa.PrimaryKeyConstraint('id')
                                             )

    op.bulk_insert(cat_images_guide_table,
                   [
                       {'id': 1, 'url': 'https://disk.yandex.ru/i/oslIRIpwgemhbg'},
                       {'id': 2, 'url': 'https://disk.yandex.ru/i/ljW6XDZoMUCj8Q'},
                       {'id': 3, 'url': 'https://disk.yandex.ru/i/-cXplw7KA_HUXg'},
                       {'id': 4, 'url': 'https://disk.yandex.ru/i/mfZOYNul5oaB_Q'},
                       {'id': 5, 'url': 'https://disk.yandex.ru/i/dAAcJAh0ngFxZw'},
                       {'id': 6, 'url': 'https://disk.yandex.ru/i/IkhDfFrTnFbrig'},
                       {'id': 7, 'url': 'https://disk.yandex.ru/i/3UnxNtFsgJ2v-A'},
                       {'id': 8, 'url': 'https://disk.yandex.ru/i/WdCwL3VF6RErWQ'},
                       {'id': 9, 'url': 'https://disk.yandex.ru/i/jRP2FGtXBcVtcA'},
                       {'id': 10, 'url': 'https://disk.yandex.ru/i/Fv8MFtPBuqFQ3g'},

                   ])

    op.create_table('channels_guide',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=60), nullable=False),
                    sa.Column('url', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
                    sa.Column('username', sa.String(length=64), nullable=False),
                    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    op.create_table('channel_subscriptions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('channel_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('subscription', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['channel_id'], ['channels_guide.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_channel_subscriptions_channel_id'), 'channel_subscriptions', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_subscriptions_user_id'), 'channel_subscriptions', ['user_id'], unique=False)
    op.create_table('credits',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('term', sa.Integer(), nullable=False),
                    sa.Column('percent', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_credits_user_id'), 'credits', ['user_id'], unique=False)
    op.create_table('deposits',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('term', sa.Integer(), nullable=False),
                    sa.Column('percent', sa.Integer(), nullable=False),
                    sa.Column('payment_date', sa.DateTime(), nullable=False),
                    sa.Column('payment_amount', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_deposits_user_id'), 'deposits', ['user_id'], unique=False)
    op.create_table('transactions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
                    sa.Column('type', sa.Enum('PURCHASE', 'CREDIT', 'DEPOSIT', 'SUBSCRIPTION', 'TRANSFER',
                                              name='transactiontype'), nullable=False),
                    sa.Column('description', sa.String(length=255), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_cats',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('cat_image_id', sa.Integer(), nullable=False),
                    sa.Column('bought_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['cat_image_id'], ['cat_images_guide.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_cats_cat_image_id'), 'user_cats', ['cat_image_id'], unique=False)
    op.create_index(op.f('ix_user_cats_user_id'), 'user_cats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_cats_user_id'), table_name='user_cats')
    op.drop_index(op.f('ix_user_cats_cat_image_id'), table_name='user_cats')
    op.drop_table('user_cats')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_deposits_user_id'), table_name='deposits')
    op.drop_table('deposits')
    op.drop_index(op.f('ix_credits_user_id'), table_name='credits')
    op.drop_table('credits')
    op.drop_index(op.f('ix_channel_subscriptions_user_id'), table_name='channel_subscriptions')
    op.drop_index(op.f('ix_channel_subscriptions_channel_id'), table_name='channel_subscriptions')
    op.drop_table('channel_subscriptions')
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('channels_guide')
    op.drop_table('cat_images_guide')
    # ### end Alembic commands ###
