"""

Revision ID: b3995e5d441e
Revises: c1b32aa0adcf
Create Date: 2025-02-02 20:06:40.516592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3995e5d441e'
down_revision: Union[str, None] = 'c1b32aa0adcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_jobs', sa.Column('apscheduler_job_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_scheduled_jobs_apscheduler_job_id'), 'scheduled_jobs', ['apscheduler_job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_jobs_apscheduler_job_id'), table_name='scheduled_jobs')
    op.drop_column('scheduled_jobs', 'apscheduler_job_id')
    # ### end Alembic commands ###
