"""

Revision ID: bfb0e0b8af56
Revises: da2241a1827d
Create Date: 2025-02-01 01:16:47.126194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb0e0b8af56'
down_revision: Union[str, None] = 'da2241a1827d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credits', sa.Column('debt', sa.Integer(), nullable=False))
    op.add_column('credits', sa.Column('closed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credits', 'closed')
    op.drop_column('credits', 'debt')
    # ### end Alembic commands ###
