"""

Revision ID: c1b32aa0adcf
Revises: 0199ae44b549
Create Date: 2025-02-01 02:09:20.380596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b32aa0adcf'
down_revision: Union[str, None] = '0199ae44b549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credits', sa.Column('remaining_debt', sa.Integer(), nullable=False))
    op.drop_column('credits', 'debt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credits', sa.Column('debt', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('credits', 'remaining_debt')
    # ### end Alembic commands ###
