"""

Revision ID: cd91062f48e8
Revises: dd2642fd743c
Create Date: 2025-01-26 02:51:22.006075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd91062f48e8'
down_revision: Union[str, None] = 'dd2642fd743c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels_guide', sa.Column('username', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels_guide', 'username')
    # ### end Alembic commands ###
