"""

Revision ID: dd2642fd743c
Revises: 3a02ebc264a4
Create Date: 2025-01-26 01:33:15.087682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd2642fd743c'
down_revision: Union[str, None] = '3a02ebc264a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_subscriptions', 'subscription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_subscriptions', sa.Column('subscription', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
