"""

Revision ID: f4e85a381cda
Revises: 21bf837adee0
Create Date: 2025-02-03 22:25:43.245411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e85a381cda'
down_revision: Union[str, None] = '21bf837adee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposits', sa.Column('completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deposits', 'completed')
    # ### end Alembic commands ###
